// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Bookstore API
//
//	TODO: do better than Bookstore API description
//	Schemes:
//	  http
//	Host: bookstore.orthodox.net
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
