// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "TODO: do better than Bookstore API description",
    "title": "Bookstore API",
    "version": "1.0.0"
  },
  "host": "bookstore.orthodox.net",
  "basePath": "/v1",
  "paths": {
    "/inventory": {
      "get": {
        "summary": "Get all available inventory",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Inventory"
              }
            }
          }
        }
      }
    },
    "/inventory/{id}": {
      "get": {
        "summary": "Get an inventory by ID",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Inventory ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Inventory"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Inventory": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "TODO: do better than Bookstore API description",
    "title": "Bookstore API",
    "version": "1.0.0"
  },
  "host": "bookstore.orthodox.net",
  "basePath": "/v1",
  "paths": {
    "/inventory": {
      "get": {
        "summary": "Get all available inventory",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Inventory"
              }
            }
          }
        }
      }
    },
    "/inventory/{id}": {
      "get": {
        "summary": "Get an inventory by ID",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "Inventory ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Inventory"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Inventory": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
}
