/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/inventory": {
    get: {
      responses: {
        /** Successful operation */
        200: {
          schema: definitions["Inventory"][];
        };
      };
    };
  };
  "/inventory/{id}": {
    get: {
      parameters: {
        path: {
          /** Inventory ID */
          id: string;
        };
      };
      responses: {
        /** Successful operation */
        200: {
          schema: definitions["Inventory"];
        };
      };
    };
  };
}

export interface definitions {
  Inventory: {
    /** Format: uuid */
    id?: string;
    name?: string;
    description?: string;
  };
}

export interface operations {}

export interface external {}
