// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/alexschexc/bookstore/web/models"
)

// GetInventoryReader is a Reader for the GetInventory structure.
type GetInventoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInventoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInventoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /inventory] GetInventory", response, response.Code())
	}
}

// NewGetInventoryOK creates a GetInventoryOK with default headers values
func NewGetInventoryOK() *GetInventoryOK {
	return &GetInventoryOK{}
}

/*
GetInventoryOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetInventoryOK struct {
	Payload []*models.Inventory
}

// IsSuccess returns true when this get inventory o k response has a 2xx status code
func (o *GetInventoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get inventory o k response has a 3xx status code
func (o *GetInventoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get inventory o k response has a 4xx status code
func (o *GetInventoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get inventory o k response has a 5xx status code
func (o *GetInventoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get inventory o k response a status code equal to that given
func (o *GetInventoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get inventory o k response
func (o *GetInventoryOK) Code() int {
	return 200
}

func (o *GetInventoryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /inventory][%d] getInventoryOK %s", 200, payload)
}

func (o *GetInventoryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /inventory][%d] getInventoryOK %s", 200, payload)
}

func (o *GetInventoryOK) GetPayload() []*models.Inventory {
	return o.Payload
}

func (o *GetInventoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
