// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInventoryIDParams creates a new GetInventoryIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryIDParams() *GetInventoryIDParams {
	return &GetInventoryIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryIDParamsWithTimeout creates a new GetInventoryIDParams object
// with the ability to set a timeout on a request.
func NewGetInventoryIDParamsWithTimeout(timeout time.Duration) *GetInventoryIDParams {
	return &GetInventoryIDParams{
		timeout: timeout,
	}
}

// NewGetInventoryIDParamsWithContext creates a new GetInventoryIDParams object
// with the ability to set a context for a request.
func NewGetInventoryIDParamsWithContext(ctx context.Context) *GetInventoryIDParams {
	return &GetInventoryIDParams{
		Context: ctx,
	}
}

// NewGetInventoryIDParamsWithHTTPClient creates a new GetInventoryIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryIDParamsWithHTTPClient(client *http.Client) *GetInventoryIDParams {
	return &GetInventoryIDParams{
		HTTPClient: client,
	}
}

/*
GetInventoryIDParams contains all the parameters to send to the API endpoint

	for the get inventory ID operation.

	Typically these are written to a http.Request.
*/
type GetInventoryIDParams struct {

	/* ID.

	   Inventory ID

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryIDParams) WithDefaults() *GetInventoryIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory ID params
func (o *GetInventoryIDParams) WithTimeout(timeout time.Duration) *GetInventoryIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory ID params
func (o *GetInventoryIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory ID params
func (o *GetInventoryIDParams) WithContext(ctx context.Context) *GetInventoryIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory ID params
func (o *GetInventoryIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory ID params
func (o *GetInventoryIDParams) WithHTTPClient(client *http.Client) *GetInventoryIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory ID params
func (o *GetInventoryIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get inventory ID params
func (o *GetInventoryIDParams) WithID(id strfmt.UUID) *GetInventoryIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get inventory ID params
func (o *GetInventoryIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
