// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteInventoryItemsIDNoContentCode is the HTTP code returned for type DeleteInventoryItemsIDNoContent
const DeleteInventoryItemsIDNoContentCode int = 204

/*
DeleteInventoryItemsIDNoContent Successful operation

swagger:response deleteInventoryItemsIdNoContent
*/
type DeleteInventoryItemsIDNoContent struct {
}

// NewDeleteInventoryItemsIDNoContent creates DeleteInventoryItemsIDNoContent with default headers values
func NewDeleteInventoryItemsIDNoContent() *DeleteInventoryItemsIDNoContent {

	return &DeleteInventoryItemsIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteInventoryItemsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteInventoryItemsIDUnauthorizedCode is the HTTP code returned for type DeleteInventoryItemsIDUnauthorized
const DeleteInventoryItemsIDUnauthorizedCode int = 401

/*
DeleteInventoryItemsIDUnauthorized Autentication information is missing or invalid

swagger:response deleteInventoryItemsIdUnauthorized
*/
type DeleteInventoryItemsIDUnauthorized struct {
	/*

	 */
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeleteInventoryItemsIDUnauthorized creates DeleteInventoryItemsIDUnauthorized with default headers values
func NewDeleteInventoryItemsIDUnauthorized() *DeleteInventoryItemsIDUnauthorized {

	return &DeleteInventoryItemsIDUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete inventory items Id unauthorized response
func (o *DeleteInventoryItemsIDUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeleteInventoryItemsIDUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete inventory items Id unauthorized response
func (o *DeleteInventoryItemsIDUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeleteInventoryItemsIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
