// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetInventoryIDHandlerFunc turns a function with the right signature into a get inventory ID handler
type GetInventoryIDHandlerFunc func(GetInventoryIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInventoryIDHandlerFunc) Handle(params GetInventoryIDParams) middleware.Responder {
	return fn(params)
}

// GetInventoryIDHandler interface for that can handle valid get inventory ID params
type GetInventoryIDHandler interface {
	Handle(GetInventoryIDParams) middleware.Responder
}

// NewGetInventoryID creates a new http.Handler for the get inventory ID operation
func NewGetInventoryID(ctx *middleware.Context, handler GetInventoryIDHandler) *GetInventoryID {
	return &GetInventoryID{Context: ctx, Handler: handler}
}

/*
	GetInventoryID swagger:route GET /inventory/{id} getInventoryId

Get an inventory by ID
*/
type GetInventoryID struct {
	Context *middleware.Context
	Handler GetInventoryIDHandler
}

func (o *GetInventoryID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetInventoryIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
