// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alexschexc/bookstore/api/models"
)

// GetInventoryIDOKCode is the HTTP code returned for type GetInventoryIDOK
const GetInventoryIDOKCode int = 200

/*
GetInventoryIDOK Successful operation

swagger:response getInventoryIdOK
*/
type GetInventoryIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Inventory `json:"body,omitempty"`
}

// NewGetInventoryIDOK creates GetInventoryIDOK with default headers values
func NewGetInventoryIDOK() *GetInventoryIDOK {

	return &GetInventoryIDOK{}
}

// WithPayload adds the payload to the get inventory Id o k response
func (o *GetInventoryIDOK) WithPayload(payload *models.Inventory) *GetInventoryIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get inventory Id o k response
func (o *GetInventoryIDOK) SetPayload(payload *models.Inventory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInventoryIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
