// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alexschexc/bookstore/api/models"
)

// GetInventoryOKCode is the HTTP code returned for type GetInventoryOK
const GetInventoryOKCode int = 200

/*
GetInventoryOK Successful operation

swagger:response getInventoryOK
*/
type GetInventoryOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Inventory `json:"body,omitempty"`
}

// NewGetInventoryOK creates GetInventoryOK with default headers values
func NewGetInventoryOK() *GetInventoryOK {

	return &GetInventoryOK{}
}

// WithPayload adds the payload to the get inventory o k response
func (o *GetInventoryOK) WithPayload(payload []*models.Inventory) *GetInventoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get inventory o k response
func (o *GetInventoryOK) SetPayload(payload []*models.Inventory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInventoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Inventory, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
