// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alexschexc/bookstore/api/models"
)

// PatchInventoryItemsIDOKCode is the HTTP code returned for type PatchInventoryItemsIDOK
const PatchInventoryItemsIDOKCode int = 200

/*
PatchInventoryItemsIDOK Successful operation

swagger:response patchInventoryItemsIdOK
*/
type PatchInventoryItemsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.InventoryItem `json:"body,omitempty"`
}

// NewPatchInventoryItemsIDOK creates PatchInventoryItemsIDOK with default headers values
func NewPatchInventoryItemsIDOK() *PatchInventoryItemsIDOK {

	return &PatchInventoryItemsIDOK{}
}

// WithPayload adds the payload to the patch inventory items Id o k response
func (o *PatchInventoryItemsIDOK) WithPayload(payload *models.InventoryItem) *PatchInventoryItemsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch inventory items Id o k response
func (o *PatchInventoryItemsIDOK) SetPayload(payload *models.InventoryItem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchInventoryItemsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchInventoryItemsIDUnauthorizedCode is the HTTP code returned for type PatchInventoryItemsIDUnauthorized
const PatchInventoryItemsIDUnauthorizedCode int = 401

/*
PatchInventoryItemsIDUnauthorized Autentication information is missing or invalid

swagger:response patchInventoryItemsIdUnauthorized
*/
type PatchInventoryItemsIDUnauthorized struct {
	/*

	 */
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewPatchInventoryItemsIDUnauthorized creates PatchInventoryItemsIDUnauthorized with default headers values
func NewPatchInventoryItemsIDUnauthorized() *PatchInventoryItemsIDUnauthorized {

	return &PatchInventoryItemsIDUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the patch inventory items Id unauthorized response
func (o *PatchInventoryItemsIDUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *PatchInventoryItemsIDUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the patch inventory items Id unauthorized response
func (o *PatchInventoryItemsIDUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *PatchInventoryItemsIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
