// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryFields inventory fields
//
// swagger:model InventoryFields
type InventoryFields struct {

	// category
	Category string `json:"category,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this inventory fields
func (m *InventoryFields) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inventory fields based on context it is used
func (m *InventoryFields) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryFields) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryFields) UnmarshalBinary(b []byte) error {
	var res InventoryFields
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
